apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AbhiTejaChapa/argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: arn:aws:eks:ap-south-1:424169040574:cluster/dev-sunnxt
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
